/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as PublicImport } from "./routes/_public";
import { Route as PrivateImport } from "./routes/_private";
import { Route as AuthImport } from "./routes/_auth";
import { Route as PrivateIndexImport } from "./routes/_private/index";
import { Route as PublicPlaygroundImport } from "./routes/_public/playground";
import { Route as AuthSignInImport } from "./routes/_auth/sign-in";
import { Route as Oauth2ProviderCallbackImport } from "./routes/oauth2.$provider.callback";

// Create/Update Routes

const PublicRoute = PublicImport.update({
  id: "/_public",
  getParentRoute: () => rootRoute,
} as any);

const PrivateRoute = PrivateImport.update({
  id: "/_private",
  getParentRoute: () => rootRoute,
} as any);

const AuthRoute = AuthImport.update({
  id: "/_auth",
  getParentRoute: () => rootRoute,
} as any);

const PrivateIndexRoute = PrivateIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => PrivateRoute,
} as any);

const PublicPlaygroundRoute = PublicPlaygroundImport.update({
  id: "/playground",
  path: "/playground",
  getParentRoute: () => PublicRoute,
} as any);

const AuthSignInRoute = AuthSignInImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => AuthRoute,
} as any);

const Oauth2ProviderCallbackRoute = Oauth2ProviderCallbackImport.update({
  id: "/oauth2/$provider/callback",
  path: "/oauth2/$provider/callback",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthImport;
      parentRoute: typeof rootRoute;
    };
    "/_private": {
      id: "/_private";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof PrivateImport;
      parentRoute: typeof rootRoute;
    };
    "/_public": {
      id: "/_public";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof PublicImport;
      parentRoute: typeof rootRoute;
    };
    "/_auth/sign-in": {
      id: "/_auth/sign-in";
      path: "/sign-in";
      fullPath: "/sign-in";
      preLoaderRoute: typeof AuthSignInImport;
      parentRoute: typeof AuthImport;
    };
    "/_public/playground": {
      id: "/_public/playground";
      path: "/playground";
      fullPath: "/playground";
      preLoaderRoute: typeof PublicPlaygroundImport;
      parentRoute: typeof PublicImport;
    };
    "/_private/": {
      id: "/_private/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof PrivateIndexImport;
      parentRoute: typeof PrivateImport;
    };
    "/oauth2/$provider/callback": {
      id: "/oauth2/$provider/callback";
      path: "/oauth2/$provider/callback";
      fullPath: "/oauth2/$provider/callback";
      preLoaderRoute: typeof Oauth2ProviderCallbackImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

interface PrivateRouteChildren {
  PrivateIndexRoute: typeof PrivateIndexRoute;
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateIndexRoute: PrivateIndexRoute,
};

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren);

interface PublicRouteChildren {
  PublicPlaygroundRoute: typeof PublicPlaygroundRoute;
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicPlaygroundRoute: PublicPlaygroundRoute,
};

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren);

export interface FileRoutesByFullPath {
  "": typeof PublicRouteWithChildren;
  "/sign-in": typeof AuthSignInRoute;
  "/playground": typeof PublicPlaygroundRoute;
  "/": typeof PrivateIndexRoute;
  "/oauth2/$provider/callback": typeof Oauth2ProviderCallbackRoute;
}

export interface FileRoutesByTo {
  "": typeof PublicRouteWithChildren;
  "/sign-in": typeof AuthSignInRoute;
  "/playground": typeof PublicPlaygroundRoute;
  "/": typeof PrivateIndexRoute;
  "/oauth2/$provider/callback": typeof Oauth2ProviderCallbackRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/_auth": typeof AuthRouteWithChildren;
  "/_private": typeof PrivateRouteWithChildren;
  "/_public": typeof PublicRouteWithChildren;
  "/_auth/sign-in": typeof AuthSignInRoute;
  "/_public/playground": typeof PublicPlaygroundRoute;
  "/_private/": typeof PrivateIndexRoute;
  "/oauth2/$provider/callback": typeof Oauth2ProviderCallbackRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | ""
    | "/sign-in"
    | "/playground"
    | "/"
    | "/oauth2/$provider/callback";
  fileRoutesByTo: FileRoutesByTo;
  to: "" | "/sign-in" | "/playground" | "/" | "/oauth2/$provider/callback";
  id:
    | "__root__"
    | "/_auth"
    | "/_private"
    | "/_public"
    | "/_auth/sign-in"
    | "/_public/playground"
    | "/_private/"
    | "/oauth2/$provider/callback";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren;
  PrivateRoute: typeof PrivateRouteWithChildren;
  PublicRoute: typeof PublicRouteWithChildren;
  Oauth2ProviderCallbackRoute: typeof Oauth2ProviderCallbackRoute;
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  Oauth2ProviderCallbackRoute: Oauth2ProviderCallbackRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_private",
        "/_public",
        "/oauth2/$provider/callback"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/sign-in"
      ]
    },
    "/_private": {
      "filePath": "_private.tsx",
      "children": [
        "/_private/"
      ]
    },
    "/_public": {
      "filePath": "_public.tsx",
      "children": [
        "/_public/playground"
      ]
    },
    "/_auth/sign-in": {
      "filePath": "_auth/sign-in.tsx",
      "parent": "/_auth"
    },
    "/_public/playground": {
      "filePath": "_public/playground.tsx",
      "parent": "/_public"
    },
    "/_private/": {
      "filePath": "_private/index.tsx",
      "parent": "/_private"
    },
    "/oauth2/$provider/callback": {
      "filePath": "oauth2.$provider.callback.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
